summarise

diff --git a/.github/workflows/draft_new_release.yaml b/.github/workflows/draft_new_release.yaml
--- a/.github/workflows/draft_new_release.yaml
+++ b/.github/workflows/draft_new_release.yaml
@@ -17,40 +17,49 @@ jobs:
       pull-requests: write
     steps:
 
-        - name: Clone Repo
-          uses: actions/checkout@v2
+      - name: Clone Repo
+        uses: actions/checkout@v2
 
-        - name: Derive Label
-          id: derive-label
-          run: |
-            new_release_number=$(echo $GITHUB_HEAD_REF | cut -d'/' -f2)
-            latest_release=$(git tag -l | grep -E "^[0-9]{1,2}\.[0-9]{1,4}\.[0-9]{1,4}\$" | sort -V | tail -1) || "0.0.0"
+      - name: Derive Label
+        id: derive-label
+        run: |
+          new_release_number=$(echo $GITHUB_HEAD_REF | cut -d'/' -f2)
+          latest_release=$(git tag -l | grep -E "^[0-9]{1,2}\.[0-9]{1,4}\.[0-9]{1,4}\$" | sort -V | tail -1) || "0.0.0"
 
-            if ! [[ $new_release_number =~ ^[0-9]{1,2}\.[0-9]{1,4}\.[0-9]{1,4}$ ]]
-            then
-                echo "Release number is invalid: $new_release_number"
-                exit 1
-            fi
-            
-            if [ "${new_release_number%%.*}" != "${latest_release%%.*}" ]
-            then
-                echo "release-label=major" >> $GITHUB_OUTPUT
-            elif [ $( cut -d '.' -f2 <<< $new_release_number) != $( cut -d '.' -f2 <<< $latest_release ) ]
-            then
-              echo "release-label=minor" >> $GITHUB_OUTPUT
-            elif [ "${new_release_number##*.}" != "${latest_release##*.}" ]
-            then
-              echo "release-label=patch" >> $GITHUB_OUTPUT
-            else
-                echo "new_release_number is $new_release_number"
-                echo "latest_release is $latest_release"
-                exit 1
-            fi
+          if ! [[ $new_release_number =~ ^[0-9]{1,2}\.[0-9]{1,4}\.[0-9]{1,4}$ ]]
+          then
+              echo "Release number is invalid: $new_release_number"
+              exit 1
+          else
+            echo "new-release-number=$new_release_number" >> $GITHUB_OUTPUT
+            echo "latest-release=$latest_release" >> $GITHUB_OUTPUT
+          fi
 
-        - name: Apply Label
-          run: gh pr edit ${{ github.event.pull_request.number }} --add-label ${{ steps.derive-label.outputs.release-label}}
-          env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          if [ "${new_release_number%%.*}" != "${latest_release%%.*}" ]
+          then
+              echo "release-label=major" >> $GITHUB_OUTPUT
+          elif [ $( cut -d '.' -f2 <<< $new_release_number) != $( cut -d '.' -f2 <<< $latest_release ) ]
+          then
+            echo "release-label=minor" >> $GITHUB_OUTPUT
+          elif [ "${new_release_number##*.}" != "${latest_release##*.}" ]
+          then
+            echo "release-label=patch" >> $GITHUB_OUTPUT
+          else
+              echo "new_release_number is $new_release_number"
+              echo "latest_release is $latest_release"
+              exit 1
+          fi
+
+      - name: Apply Label
+        run: gh pr edit ${{ github.event.pull_request.number }} --add-label ${{ steps.derive-label.outputs.release-label}}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Summarise
+        run: |
+          echo "Release Number (derived from branch): `${{ steps.derive-label.outputs.new-release-number }}`"
+          echo "Previous Release (latest tag):  `${{ steps.derive-label.outputs.latest-release }}`"
+          echo "Release label is `${{ steps.derive-label.outputs.release-label }}`"
 
   update_release_draft:
     name: Update Release Draft
